### ISSUE TITLE
Using LQL in Python example not working: TypeError: a bytes-like object is required, not 'str

### ISSUE THREAD

**Issue by t29j** [Checkmk/checkmk-docs#60]
Hello,

The example in section 2.2. Using LQL in Python is not working
https://docs.checkmk.com/latest/en/livestatus.html#heading__using_lql_in_python

```
OMD[central]:~$ python3 live_example.py 
Traceback (most recent call last):
  File "/opt/omd/sites/central/live_example.py", line 17, in <module>
    sock.sendall("GET status\nOutputFormat: json\n")
TypeError: a bytes-like object is required, not 'str'
```

Would be nice if there would be a functional code snipped.

**Comment by sebkir** [comment]
Fixed with commit 5a8c233c78e2d5013458881b15fd73ee77fe07a9
