### ISSUE TITLE
How to integrate checkmk with Moogsoft AIOps with script

### ISSUE THREAD

**Issue by mickey2501** [Checkmk/checkmk-docs#62]
Hi,

Idea here is to whatever the events are generated in checkMK it should forward those event notifications from CheckMK to Moogsoft AIOps webhook api which will then take care of creating the incidents in ServiceNow. I know this will be done via custom script but I am not aware of that script.

Can someone suggest how this can be implemented? Is there a prewritten custom script from CheckMK to forward the event notifications? I will be glad if someone have that script or can prepare it for me?

**Comment by mschlenker** [comment]
There are several possibilities. First is using a custom notification script to forward events that trigger notifications to a script that calls the Moogsoft API:

https://docs.checkmk.com/latest/en/notifications.html?lquery=notifi#scripts

A second, more flexible way that also involves more wore is directly working on the Livestatus interface:

https://docs.checkmk.com/latest/en/livestatus.html?lquery=livestat

**Comment by mschlenker** [comment]
I am closing here since this belongs to the forum. CU there!
